# Generated by Django 5.0.6 on 2026-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='issue_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
